// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BrokerProto.proto

package com.utm.common.rcp.broker;

public interface BrokerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.utm.common.BrokerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>string responseCode = 2;</code>
   * @return The responseCode.
   */
  java.lang.String getResponseCode();
  /**
   * <code>string responseCode = 2;</code>
   * @return The bytes for responseCode.
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();
}
