// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BrokerProto.proto

package com.utm.common.rcp.broker;

public final class BrokerProto {
  private BrokerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_BrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_BrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_BrokerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_BrokerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BrokerProto.proto\022\016com.utm.common\";\n\rB" +
      "rokerRequest\022\n\n\002id\030\001 \001(\005\022\r\n\005topic\030\002 \001(\t\022" +
      "\017\n\007message\030\003 \001(\t\"?\n\016BrokerResponse\022\027\n\017re" +
      "sponseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(" +
      "\t2R\n\006Broker\022H\n\005hello\022\035.com.utm.common.Br" +
      "okerRequest\032\036.com.utm.common.BrokerRespo" +
      "nse0\001B\035\n\031com.utm.common.rcp.brokerP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_utm_common_BrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_utm_common_BrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_BrokerRequest_descriptor,
        new java.lang.String[] { "Id", "Topic", "Message", });
    internal_static_com_utm_common_BrokerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_utm_common_BrokerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_BrokerResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
