// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscriber.proto

package com.utm.common.rcp.subscriber;

public interface SubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.utm.common.SubscribeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();
}
