// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscriber.proto

package com.utm.common.rcp.subscriber;

public final class SubscriberOuterClass {
  private SubscriberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_SubscribeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_SubscribeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Subscriber.proto\022\016com.utm.common\"2\n\020Su" +
      "bscribeRequest\022\r\n\005topic\030\001 \001(\t\022\017\n\007address" +
      "\030\002 \001(\t\"&\n\021SubscribeResponse\022\021\n\tisSuccess" +
      "\030\001 \001(\0102^\n\nSubscriber\022P\n\tsubscribe\022 .com." +
      "utm.common.SubscribeRequest\032!.com.utm.co" +
      "mmon.SubscribeResponseB!\n\035com.utm.common" +
      ".rcp.subscriberP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_utm_common_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_utm_common_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_SubscribeRequest_descriptor,
        new java.lang.String[] { "Topic", "Address", });
    internal_static_com_utm_common_SubscribeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_utm_common_SubscribeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_SubscribeResponse_descriptor,
        new java.lang.String[] { "IsSuccess", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
