// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscriber.proto

package com.utm.common.rcp.subscriber;

public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.utm.common.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
