// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Publisher.proto

package com.utm.common.rcp.publisher;

public final class PublisherOuterClass {
  private PublisherOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_Payload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_utm_common_PublishResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_utm_common_PublishResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Publisher.proto\022\016com.utm.common\"5\n\007Pay" +
      "load\022\n\n\002id\030\001 \001(\005\022\r\n\005topic\030\002 \001(\t\022\017\n\007messa" +
      "ge\030\003 \001(\t\":\n\016PublishRequest\022(\n\007payload\030\001 " +
      "\003(\0132\027.com.utm.common.Payload\"$\n\017PublishR" +
      "esponse\022\021\n\tisSuccess\030\001 \001(\0102^\n\tPublisher\022" +
      "Q\n\016publishMessage\022\036.com.utm.common.Publi" +
      "shRequest\032\037.com.utm.common.PublishRespon" +
      "seB \n\034com.utm.common.rcp.publisherP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_utm_common_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_utm_common_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_Payload_descriptor,
        new java.lang.String[] { "Id", "Topic", "Message", });
    internal_static_com_utm_common_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_utm_common_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_PublishRequest_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_com_utm_common_PublishResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_utm_common_PublishResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_utm_common_PublishResponse_descriptor,
        new java.lang.String[] { "IsSuccess", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
