// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Publisher.proto

package com.utm.common.rcp.publisher;

public interface PublishResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.utm.common.PublishResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();
}
