// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Publisher.proto

package com.utm.common.rcp.publisher;

public interface PublishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.utm.common.PublishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  java.util.List<com.utm.common.rcp.publisher.Payload> 
      getPayloadList();
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  com.utm.common.rcp.publisher.Payload getPayload(int index);
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  int getPayloadCount();
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  java.util.List<? extends com.utm.common.rcp.publisher.PayloadOrBuilder> 
      getPayloadOrBuilderList();
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  com.utm.common.rcp.publisher.PayloadOrBuilder getPayloadOrBuilder(
      int index);
}
