// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Publisher.proto

package com.utm.common.rcp.publisher;

/**
 * Protobuf type {@code com.utm.common.PublishRequest}
 */
public  final class PublishRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.utm.common.PublishRequest)
    PublishRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PublishRequest.newBuilder() to construct.
  private PublishRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PublishRequest() {
    payload_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PublishRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PublishRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              payload_ = new java.util.ArrayList<com.utm.common.rcp.publisher.Payload>();
              mutable_bitField0_ |= 0x00000001;
            }
            payload_.add(
                input.readMessage(com.utm.common.rcp.publisher.Payload.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        payload_ = java.util.Collections.unmodifiableList(payload_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.utm.common.rcp.publisher.PublisherOuterClass.internal_static_com_utm_common_PublishRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.utm.common.rcp.publisher.PublisherOuterClass.internal_static_com_utm_common_PublishRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.utm.common.rcp.publisher.PublishRequest.class, com.utm.common.rcp.publisher.PublishRequest.Builder.class);
  }

  public static final int PAYLOAD_FIELD_NUMBER = 1;
  private java.util.List<com.utm.common.rcp.publisher.Payload> payload_;
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  public java.util.List<com.utm.common.rcp.publisher.Payload> getPayloadList() {
    return payload_;
  }
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  public java.util.List<? extends com.utm.common.rcp.publisher.PayloadOrBuilder> 
      getPayloadOrBuilderList() {
    return payload_;
  }
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  public com.utm.common.rcp.publisher.Payload getPayload(int index) {
    return payload_.get(index);
  }
  /**
   * <code>repeated .com.utm.common.Payload payload = 1;</code>
   */
  public com.utm.common.rcp.publisher.PayloadOrBuilder getPayloadOrBuilder(
      int index) {
    return payload_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < payload_.size(); i++) {
      output.writeMessage(1, payload_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < payload_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, payload_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.utm.common.rcp.publisher.PublishRequest)) {
      return super.equals(obj);
    }
    com.utm.common.rcp.publisher.PublishRequest other = (com.utm.common.rcp.publisher.PublishRequest) obj;

    if (!getPayloadList()
        .equals(other.getPayloadList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.utm.common.rcp.publisher.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.utm.common.rcp.publisher.PublishRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.utm.common.PublishRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.utm.common.PublishRequest)
      com.utm.common.rcp.publisher.PublishRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.utm.common.rcp.publisher.PublisherOuterClass.internal_static_com_utm_common_PublishRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.utm.common.rcp.publisher.PublisherOuterClass.internal_static_com_utm_common_PublishRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.utm.common.rcp.publisher.PublishRequest.class, com.utm.common.rcp.publisher.PublishRequest.Builder.class);
    }

    // Construct using com.utm.common.rcp.publisher.PublishRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPayloadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        payloadBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.utm.common.rcp.publisher.PublisherOuterClass.internal_static_com_utm_common_PublishRequest_descriptor;
    }

    @java.lang.Override
    public com.utm.common.rcp.publisher.PublishRequest getDefaultInstanceForType() {
      return com.utm.common.rcp.publisher.PublishRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.utm.common.rcp.publisher.PublishRequest build() {
      com.utm.common.rcp.publisher.PublishRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.utm.common.rcp.publisher.PublishRequest buildPartial() {
      com.utm.common.rcp.publisher.PublishRequest result = new com.utm.common.rcp.publisher.PublishRequest(this);
      int from_bitField0_ = bitField0_;
      if (payloadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.payload_ = payload_;
      } else {
        result.payload_ = payloadBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.utm.common.rcp.publisher.PublishRequest) {
        return mergeFrom((com.utm.common.rcp.publisher.PublishRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.utm.common.rcp.publisher.PublishRequest other) {
      if (other == com.utm.common.rcp.publisher.PublishRequest.getDefaultInstance()) return this;
      if (payloadBuilder_ == null) {
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
      } else {
        if (!other.payload_.isEmpty()) {
          if (payloadBuilder_.isEmpty()) {
            payloadBuilder_.dispose();
            payloadBuilder_ = null;
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
            payloadBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayloadFieldBuilder() : null;
          } else {
            payloadBuilder_.addAllMessages(other.payload_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.utm.common.rcp.publisher.PublishRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.utm.common.rcp.publisher.PublishRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.utm.common.rcp.publisher.Payload> payload_ =
      java.util.Collections.emptyList();
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        payload_ = new java.util.ArrayList<com.utm.common.rcp.publisher.Payload>(payload_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.utm.common.rcp.publisher.Payload, com.utm.common.rcp.publisher.Payload.Builder, com.utm.common.rcp.publisher.PayloadOrBuilder> payloadBuilder_;

    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public java.util.List<com.utm.common.rcp.publisher.Payload> getPayloadList() {
      if (payloadBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payload_);
      } else {
        return payloadBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public int getPayloadCount() {
      if (payloadBuilder_ == null) {
        return payload_.size();
      } else {
        return payloadBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public com.utm.common.rcp.publisher.Payload getPayload(int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);
      } else {
        return payloadBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder setPayload(
        int index, com.utm.common.rcp.publisher.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder setPayload(
        int index, com.utm.common.rcp.publisher.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder addPayload(com.utm.common.rcp.publisher.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder addPayload(
        int index, com.utm.common.rcp.publisher.Payload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(index, value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder addPayload(
        com.utm.common.rcp.publisher.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder addPayload(
        int index, com.utm.common.rcp.publisher.Payload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder addAllPayload(
        java.lang.Iterable<? extends com.utm.common.rcp.publisher.Payload> values) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
      } else {
        payloadBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        payloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public Builder removePayload(int index) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.remove(index);
        onChanged();
      } else {
        payloadBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public com.utm.common.rcp.publisher.Payload.Builder getPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public com.utm.common.rcp.publisher.PayloadOrBuilder getPayloadOrBuilder(
        int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);  } else {
        return payloadBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public java.util.List<? extends com.utm.common.rcp.publisher.PayloadOrBuilder> 
         getPayloadOrBuilderList() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payload_);
      }
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public com.utm.common.rcp.publisher.Payload.Builder addPayloadBuilder() {
      return getPayloadFieldBuilder().addBuilder(
          com.utm.common.rcp.publisher.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public com.utm.common.rcp.publisher.Payload.Builder addPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().addBuilder(
          index, com.utm.common.rcp.publisher.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .com.utm.common.Payload payload = 1;</code>
     */
    public java.util.List<com.utm.common.rcp.publisher.Payload.Builder> 
         getPayloadBuilderList() {
      return getPayloadFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.utm.common.rcp.publisher.Payload, com.utm.common.rcp.publisher.Payload.Builder, com.utm.common.rcp.publisher.PayloadOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.utm.common.rcp.publisher.Payload, com.utm.common.rcp.publisher.Payload.Builder, com.utm.common.rcp.publisher.PayloadOrBuilder>(
                payload_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.utm.common.PublishRequest)
  }

  // @@protoc_insertion_point(class_scope:com.utm.common.PublishRequest)
  private static final com.utm.common.rcp.publisher.PublishRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.utm.common.rcp.publisher.PublishRequest();
  }

  public static com.utm.common.rcp.publisher.PublishRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishRequest>
      PARSER = new com.google.protobuf.AbstractParser<PublishRequest>() {
    @java.lang.Override
    public PublishRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PublishRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PublishRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.utm.common.rcp.publisher.PublishRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

